<template>
    <option class="text-black" selected>&#127760; Select Your Country</option>
    <option class="text-black">Afghanistan</option>
    <option class="text-black">Åland Islands</option>
    <option class="text-black">Albania</option>
    <option class="text-black">Algeria</option>
    <option class="text-black">American Samoa</option>
    <option class="text-black">Andorra</option>
    <option class="text-black">Angola</option>
    <option class="text-black">Anguilla</option>
    <option class="text-black">Antarctica</option>
    <option class="text-black">Antigua and Barbuda</option>
    <option class="text-black">Argentina</option>
    <option class="text-black">Armenia</option>
    <option class="text-black">Aruba</option>
    <option class="text-black">Australia</option>
    <option class="text-black">Austria</option>
    <option class="text-black">Azerbaijan</option>
    <option class="text-black">Bahamas</option>
    <option class="text-black">Bahrain</option>
    <option class="text-black">Bangladesh</option>
    <option class="text-black">Barbados</option>
    <option class="text-black">Belarus</option>
    <option class="text-black">Belgium</option>
    <option class="text-black">Belize</option>
    <option class="text-black">Benin</option>
    <option class="text-black">Bermuda</option>
    <option class="text-black">Bhutan</option>
    <option class="text-black">Bolivia</option>
    <option class="text-black">Bosnia and Herzegovina</option>
    <option class="text-black">Botswana</option>
    <option class="text-black">Bouvet Island</option>
    <option class="text-black">Brazil</option>
    <option class="text-black">British Indian Ocean Territory</option>
    <option class="text-black">Brunei Darussalam</option>
    <option class="text-black">Bulgaria</option>
    <option class="text-black">Burkina Faso</option>
    <option class="text-black">Burundi</option>
    <option class="text-black">Cambodia</option>
    <option class="text-black">Cameroon</option>
    <option class="text-black">Canada</option>
    <option class="text-black">Cape Verde</option>
    <option class="text-black">Cayman Islands</option>
    <option class="text-black">Central African Republic</option>
    <option class="text-black">Chad</option>
    <option class="text-black">Chile</option>
    <option class="text-black">China</option>
    <option class="text-black">Christmas Island</option>
    <option class="text-black">Cocos (Keeling) Islands</option>
    <option class="text-black">Colombia</option>
    <option class="text-black">Comoros</option>
    <option class="text-black">Congo</option>
    <option class="text-black">Congo, The Democratic Republic of The</option>
    <option class="text-black">Cook Islands</option>
    <option class="text-black">Costa Rica</option>
    <option class="text-black">Cote D'ivoire</option>
    <option class="text-black">Croatia</option>
    <option class="text-black">Cuba</option>
    <option class="text-black">Cyprus</option>
    <option class="text-black">Czech Republic</option>
    <option class="text-black">Denmark</option>
    <option class="text-black">Djibouti</option>
    <option class="text-black">Dominica</option>
    <option class="text-black">Dominican Republic</option>
    <option class="text-black">Ecuador</option>
    <option class="text-black">Egypt</option>
    <option class="text-black">El Salvador</option>
    <option class="text-black">Equatorial Guinea</option>
    <option class="text-black">Eritrea</option>
    <option class="text-black">Estonia</option>
    <option class="text-black">Ethiopia</option>
    <option class="text-black">Falkland Islands (Malvinas)</option>
    <option class="text-black">Faroe Islands</option>
    <option class="text-black">Fiji</option>
    <option class="text-black">Finland</option>
    <option class="text-black">France</option>
    <option class="text-black">French Guiana</option>
    <option class="text-black">French Polynesia</option>
    <option class="text-black">French Southern Territories</option>
    <option class="text-black">Gabon</option>
    <option class="text-black">Gambia</option>
    <option class="text-black">Georgia</option>
    <option class="text-black">Germany</option>
    <option class="text-black">Ghana</option>
    <option class="text-black">Gibraltar</option>
    <option class="text-black">Greece</option>
    <option class="text-black">Greenland</option>
    <option class="text-black">Grenada</option>
    <option class="text-black">Guadeloupe</option>
    <option class="text-black">Guam</option>
    <option class="text-black">Guatemala</option>
    <option class="text-black">Guernsey</option>
    <option class="text-black">Guinea</option>
    <option class="text-black">Guinea-bissau</option>
    <option class="text-black">Guyana</option>
    <option class="text-black">Haiti</option>
    <option class="text-black">Heard Island and Mcdonald Islands</option>
    <option class="text-black">Holy See (Vatican City State)</option>
    <option class="text-black">Honduras</option>
    <option class="text-black">Hong Kong</option>
    <option class="text-black">Hungary</option>
    <option class="text-black">Iceland</option>
    <option class="text-black">India</option>
    <option class="text-black">Indonesia</option>
    <option class="text-black">Iran, Islamic Republic of</option>
    <option class="text-black">Iraq</option>
    <option class="text-black">Ireland</option>
    <option class="text-black">Isle of Man</option>
    <option class="text-black">Italy</option>
    <option class="text-black">Jamaica</option>
    <option class="text-black">Japan</option>
    <option class="text-black">Jersey</option>
    <option class="text-black">Jordan</option>
    <option class="text-black">Kazakhstan</option>
    <option class="text-black">Kenya</option>
    <option class="text-black">Kiribati</option>
    <option class="text-black">Korea, Democratic People's Republic of</option>
    <option class="text-black">Korea</option>
    <option class="text-black">Kuwait</option>
    <option class="text-black">Kyrgyzstan</option>
    <option class="text-black">Lao People's Democratic Republic</option>
    <option class="text-black">Latvia</option>
    <option class="text-black">Lebanon</option>
    <option class="text-black">Lesotho</option>
    <option class="text-black">Liberia</option>
    <option class="text-black">Libya</option>
    <option class="text-black">Liechtenstein</option>
    <option class="text-black">Lithuania</option>
    <option class="text-black">Luxembourg</option>
    <option class="text-black">Macao</option>
    <option class="text-black">Macedonia</option>
    <option class="text-black">Madagascar</option>
    <option class="text-black">Malawi</option>
    <option class="text-black">Malaysia</option>
    <option class="text-black">Maldives</option>
    <option class="text-black">Mali</option>
    <option class="text-black">Malta</option>
    <option class="text-black">Marshall Islands</option>
    <option class="text-black">Martinique</option>
    <option class="text-black">Mauritania</option>
    <option class="text-black">Mauritius</option>
    <option class="text-black">Mayotte</option>
    <option class="text-black">Mexico</option>
    <option class="text-black">Micronesia</option>
    <option class="text-black">Moldova</option>
    <option class="text-black">Monaco</option>
    <option class="text-black">Mongolia</option>
    <option class="text-black">Montenegro</option>
    <option class="text-black">Montserrat</option>
    <option class="text-black">Morocco</option>
    <option class="text-black">Mozambique</option>
    <option class="text-black">Myanmar</option>
    <option class="text-black">Namibia</option>
    <option class="text-black">Nauru</option>
    <option class="text-black">Nepal</option>
    <option class="text-black">Netherlands</option>
    <option class="text-black">Netherlands Antilles</option>
    <option class="text-black">New Caledonia</option>
    <option class="text-black">New Zealand</option>
    <option class="text-black">Nicaragua</option>
    <option class="text-black">Niger</option>
    <option class="text-black">Nigeria</option>
    <option class="text-black">Niue</option>
    <option class="text-black">Norfolk Island</option>
    <option class="text-black">Northern Mariana Islands</option>
    <option class="text-black">Norway</option>
    <option class="text-black">Oman</option>
    <option class="text-black">Pakistan</option>
    <option class="text-black">Palau</option>
    <option class="text-black">Palestine</option>
    <option class="text-black">Panama</option>
    <option class="text-black">Papua New Guinea</option>
    <option class="text-black">Paraguay</option>
    <option class="text-black">Peru</option>
    <option class="text-black">Philippines</option>
    <option class="text-black">Pitcairn</option>
    <option class="text-black">Poland</option>
    <option class="text-black">Portugal</option>
    <option class="text-black">Puerto Rico</option>
    <option class="text-black">Qatar</option>
    <option class="text-black">Reunion</option>
    <option class="text-black">Romania</option>
    <option class="text-black">Russia</option>
    <option class="text-black">Rwanda</option>
    <option class="text-black">Saint Helena</option>
    <option class="text-black">Saint Kitts and Nevis</option>
    <option class="text-black">Saint Lucia</option>
    <option class="text-black">Saint Pierre and Miquelon</option>
    <option class="text-black">Saint Vincent and The Grenadines</option>
    <option class="text-black">Samoa</option>
    <option class="text-black">San Marino</option>
    <option class="text-black">Sao Tome and Principe</option>
    <option class="text-black">Saudi Arabia</option>
    <option class="text-black">Senegal</option>
    <option class="text-black">Serbia</option>
    <option class="text-black">Seychelles</option>
    <option class="text-black">Sierra Leone</option>
    <option class="text-black">Singapore</option>
    <option class="text-black">Slovakia</option>
    <option class="text-black">Slovenia</option>
    <option class="text-black">Solomon Islands</option>
    <option class="text-black">Somalia</option>
    <option class="text-black">South Africa</option>
    <option class="text-black">South Georgia and The South Sandwich Islands</option>
    <option class="text-black">Spain</option>
    <option class="text-black">Sri Lanka</option>
    <option class="text-black">Sudan</option>
    <option class="text-black">Suriname</option>
    <option class="text-black">Svalbard and Jan Mayen</option>
    <option class="text-black">Swaziland</option>
    <option class="text-black">Sweden</option>
    <option class="text-black">Switzerland</option>
    <option class="text-black">Syria</option>
    <option class="text-black">Taiwan</option>
    <option class="text-black">Tajikistan</option>
    <option class="text-black">Tanzania, United Republic of</option>
    <option class="text-black">Thailand</option>
    <option class="text-black">Timor-leste</option>
    <option class="text-black">Togo</option>
    <option class="text-black">Tokelau</option>
    <option class="text-black">Tonga</option>
    <option class="text-black">Trinidad and Tobago</option>
    <option class="text-black">Tunisia</option>
    <option class="text-black">Turkey</option>
    <option class="text-black">Turkmenistan</option>
    <option class="text-black">Turks and Caicos Islands</option>
    <option class="text-black">Tuvalu</option>
    <option class="text-black">Uganda</option>
    <option class="text-black">Ukraine</option>
    <option class="text-black">United Arab Emirates</option>
    <option class="text-black">United Kingdom</option>
    <option class="text-black">United States</option>
    <option class="text-black">United States Minor Outlying Islands</option>
    <option class="text-black">Uruguay</option>
    <option class="text-black">Uzbekistan</option>
    <option class="text-black">Vanuatu</option>
    <option class="text-black">Venezuela</option>
    <option class="text-black">Viet Nam</option>
    <option class="text-black">Virgin Islands, British</option>
    <option class="text-black">Virgin Islands, U.S.</option>
    <option class="text-black">Wallis and Futuna</option>
    <option class="text-black">Western Sahara</option>
    <option class="text-black">Yemen</option>
    <option class="text-black">Zambia</option>
    <option class="text-black">Zimbabwe</option>
</template>